// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Test(props) {
  return JsxRuntime.jsx("div", {
              children: "Hello World"
            });
}

function print_key(k) {
  console.log(k.key);
}

var make = Test;

export {
  make ,
  print_key ,
}
/* react/jsx-runtime Not a pure module */
